name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Set Ruby version to 3.0 or higher
          bundler: true   
      - name: Update RubyGems
        run: |
          gem update --system 3.3.22  # Ensure RubyGems version is >= 3.3.22

      - name: Install dependencies
        run: |
          bundle install
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'

